version: '3.8'

services:
  board-service:
    build:
      context: ../board-application/
    container_name: board_service
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ./target:/app

  postgres:
    image: postgres:16-alpine
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_DB=boardservice
      - POSTGRES_USER=myapp
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - app-network
    volumes:
      - ./database:/docker-entrypoint-initdb.d

networks:
  app-network:
    driver: bridge