spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/boardservice
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
